<?php

namespace EcJobHunting\Admin\Registry;

use EcJobHunting\Front\SiteSettings;

class AcfFields
{
    public function __construct()
    {
        if (function_exists('acf_add_local_field_group')) {
            $this->vacancyFields();
            $this->siteSettingsFields();
            $this->cvFields();
            $this->userFields();
            $this->employerFields();
        }
        //job settings
        add_filter('acf/load_field/key=field_5fecd57ec26b9', [$this, 'benefitsChoices']);
        add_filter('acf/load_field/key=field_5fecd839c41cf', [$this, 'agreementChoices']);
        add_filter('acf/load_field/key=field_compensation_currency', [$this, 'currencyChoices']);
        add_filter('acf/load_field/key=field_compensation_period', [$this, 'compensationPeriodChoices']);
    }

    private function vacancyFields()
    {
        acf_add_local_field_group(
            [
                'key' => 'group_5fecd546cb707',
                'title' => 'Vacancy Details',
                'fields' => [
                    [
                        'key' => 'field_5fecd57ec26b9',
                        'label' => 'Benefits',
                        'name' => 'benefits',
                        'type' => 'checkbox',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                        'layout' => 'vertical',
                        'toggle' => 0,
                        'return_format' => 'value',
                        'save_custom' => 0,
                    ],
                    [
                        'key' => 'field_5fecd6a9c26bb',
                        'label' => 'Compensation Range',
                        'name' => 'compensation_range',
                        'type' => 'group',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                        'layout' => 'block',
                        'sub_fields' => [
                            [
                                'key' => 'field_5fecd6e2c41c7',
                                'label' => 'From',
                                'name' => 'from',
                                'type' => 'text',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => [
                                    'width' => '50',
                                    'class' => '',
                                    'id' => '',
                                ],
                                'default_value' => '',
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                                'maxlength' => '',
                            ],
                            [
                                'key' => 'field_5fecd6efc41c8',
                                'label' => 'To',
                                'name' => 'to',
                                'type' => 'text',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => [
                                    'width' => '50',
                                    'class' => '',
                                    'id' => '',
                                ],
                                'default_value' => '',
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                                'maxlength' => '',
                            ],
                        ],
                    ],
                    [
                        'key' => 'field_compensation_currency',
                        'label' => 'Compensation Currency',
                        'name' => 'compensation_currency',
                        'type' => 'select',
                        'allow_custom' => 0,
                        'layout' => 'vertical',
                        'toggle' => 0,
                        'return_format' => 'value',
                        'save_custom' => 0,
                        'wrapper' => [
                            'width' => '40',
                            'class' => '',
                            'id' => '',
                        ],
                    ],
                    [
                        'key' => 'field_compensation_period',
                        'label' => 'Compensation Period',
                        'name' => 'compensation_period',
                        'type' => 'select',
                        'allow_custom' => 0,
                        'layout' => 'vertical',
                        'toggle' => 0,
                        'return_format' => 'value',
                        'save_custom' => 0,
                        'wrapper' => [
                            'width' => '40',
                            'class' => '',
                            'id' => '',
                        ],
                    ],
                    [
                        'key' => 'field_is_commission_included',
                        'label' => 'Plus commission',
                        'name' => 'is_commission_included',
                        'type' => 'true_false',
                        'default' => 0,
                        'wrapper' => [
                            'width' => '20',
                            'class' => '',
                            'id' => '',
                        ],
                    ],
                    [
                        'key' => 'field_5fecd722c41c9',
                        'label' => 'Street Address',
                        'name' => 'street_address',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                    ],
                    [
                        'key' => 'field_5fecd75ac41ca',
                        'label' => 'Hiring Company',
                        'name' => 'hiring_company',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                    ],
                    [
                        'key' => 'field_5fecd775c41cb',
                        'label' => 'Why Work at This Company',
                        'name' => 'why_work_at_this_company',
                        'type' => 'textarea',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                    ],
                    [
                        'key' => 'field_5fecd781c41cc',
                        'label' => 'Hiring Company Description',
                        'name' => 'hiring_company_description',
                        'type' => 'textarea',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                    ],

                    [
                        'key' => 'field_5fecd7d5c41ce',
                        'label' => 'Alert emails with new candidates will be sent to',
                        'name' => 'emails_to_inform',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                    ],
                    [
                        'key' => 'field_5fecd839c41cf',
                        'label' => 'Additional options',
                        'name' => 'additional_options',
                        'type' => 'checkbox',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                        'layout' => 'vertical',
                        'toggle' => 0,
                        'return_format' => 'value',
                        'save_custom' => 0,
                    ],
                ],
                'location' => [
                    [
                        [
                            'param' => 'post_type',
                            'operator' => '==',
                            'value' => 'vacancy',
                        ],
                    ],
                ],
                'menu_order' => 0,
                'position' => 'normal',
                'style' => 'default',
                'label_placement' => 'top',
                'instruction_placement' => 'label',
                'hide_on_screen' => '',
                'active' => true,
                'description' => '',
            ]
        );
        acf_add_local_field_group(
            [
                'key' => 'group_5ff2004e4555a',
                'title' => 'Job Statistic',
                'fields' => [
                    [
                        'key' => 'field_5ff2005d88a3e',
                        'label' => 'Visitors',
                        'name' => 'visitors',
                        'type' => 'number',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                        'default_value' => 0,
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'min' => 0,
                        'max' => '',
                        'step' => 1,
                    ],
                    [
                        'key' => 'field_5ff2007688a3f',
                        'label' => 'Applied',
                        'name' => 'applied',
                        'type' => 'user',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                        'role' => [
                            0 => 'candidate',
                        ],
                        'allow_null' => 0,
                        'multiple' => 1,
                        'return_format' => 'id',
                    ],
                ],
                'location' => [
                    [
                        [
                            'param' => 'post_type',
                            'operator' => '==',
                            'value' => 'vacancy',
                        ],
                    ],
                ],
                'menu_order' => 0,
                'position' => 'side',
                'style' => 'default',
                'label_placement' => 'top',
                'instruction_placement' => 'label',
                'hide_on_screen' => '',
                'active' => true,
                'description' => '',
            ]
        );
    }

    private function siteSettingsFields()
    {
        acf_add_local_field_group(
            [
                'key' => 'group_5fecf4a46d935',
                'title' => 'General theme settings',
                'fields' => [
                    [
                        'key' => 'field_5fecf67f428a4',
                        'label' => 'Header Settings',
                        'name' => '',
                        'type' => 'tab',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                        'placement' => 'top',
                        'endpoint' => 0,
                    ],
                    [
                        'key' => 'field_5fecf4b8b7889',
                        'label' => 'Logo',
                        'name' => 'logo',
                        'type' => 'image',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                        'return_format' => 'url',
                        'preview_size' => 'full',
                        'library' => 'uploadedTo',
                        'min_width' => '',
                        'min_height' => '',
                        'min_size' => '',
                        'max_width' => '',
                        'max_height' => '',
                        'max_size' => '',
                        'mime_types' => '',
                    ],
                    [
                        'key' => 'field_footer_tab',
                        'label' => 'Footer Settings',
                        'name' => '',
                        'type' => 'tab',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                        'placement' => 'top',
                        'endpoint' => 0,
                    ],
                    [
                        'key' => 'field_about_us_description',
                        'label' => 'About Us Description',
                        'name' => 'footer_about_us_description',
                        'type' => 'textarea',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                    ],
                    [
                        'key' => 'field_contacts_tab',
                        'label' => 'Contact Information',
                        'name' => '',
                        'type' => 'tab',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                        'placement' => 'top',
                        'endpoint' => 0,
                    ],
                    [
                        'key' => 'field_site_social_profiles',
                        'label' => 'Social profiles',
                        'name' => 'site_social_profiles',
                        'type' => 'repeater',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                        'collapsed' => '',
                        'min' => 0,
                        'max' => 0,
                        'layout' => 'table',
                        'button_label' => '',
                        'sub_fields' => [
                            [
                                'key' => 'field_site_social_network_name',
                                'label' => 'Social Network Name',
                                'name' => 'site_social_network_name',
                                'type' => 'text',
                                'instructions' => '',
                                'required' => 1,
                                'conditional_logic' => 0,
                                'wrapper' => [
                                    'width' => '33.3',
                                    'class' => '',
                                    'id' => '',
                                ],
                                'default_value' => '',
                                'placeholder' => '',
                            ],
                            [
                                'key' => 'field_site_social_profile_url',
                                'label' => 'Profile Url',
                                'name' => 'site_social_profile_url',
                                'type' => 'url',
                                'instructions' => '',
                                'required' => 1,
                                'conditional_logic' => 0,
                                'wrapper' => [
                                    'width' => '33.3',
                                    'class' => '',
                                    'id' => '',
                                ],
                                'default_value' => '',
                                'placeholder' => '',
                            ],
                            [
                                'key' => 'field_site_social_profile_name',
                                'label' => 'Profile Name',
                                'name' => 'site_social_profile_name',
                                'type' => 'text',
                                'instructions' => '',
                                'required' => 1,
                                'conditional_logic' => 0,
                                'wrapper' => [
                                    'width' => '33.3',
                                    'class' => '',
                                    'id' => '',
                                ],
                                'default_value' => '',
                                'placeholder' => '',
                            ],
                        ]
                    ],
                    [
                        'key' => 'field_site_phone',
                        'label' => 'Phone number',
                        'name' => 'site_phone',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => [
                            'width' => '50',
                            'class' => '',
                            'id' => '',
                        ],
                        'default_value' => '',
                        'placeholder' => '',
                    ],
                    [
                        'key' => 'field_site_email',
                        'label' => 'Email',
                        'name' => 'site_email',
                        'type' => 'email',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => [
                            'width' => '50',
                            'class' => '',
                            'id' => '',
                        ],
                        'default_value' => '',
                        'placeholder' => '',
                    ],
                    [
                        'key' => 'field_search_tab',
                        'label' => 'Search Settings',
                        'name' => '',
                        'type' => 'tab',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                        'placement' => 'top',
                        'endpoint' => 0,
                    ],
                    [
                        'key' => 'field_search_page_url',
                        'label' => 'Search page URL',
                        'name' => 'search_page_url',
                        'type' => 'page_link',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                        'return_format' => 'url',
                    ],
                ],
                'location' => [
                    [
                        [
                            'param' => 'options_page',
                            'operator' => '==',
                            'value' => 'site-settings',
                        ],
                    ],
                ],
                'menu_order' => 0,
                'position' => 'normal',
                'style' => 'default',
                'label_placement' => 'top',
                'instruction_placement' => 'label',
                'hide_on_screen' => '',
                'active' => true,
                'description' => '',
            ]
        );
        acf_add_local_field_group(
            [
                'key' => 'group_5ff88c88c1962',
                'title' => 'User Settings',
                'fields' => [
                    [
                        'key' => 'field_5ff88c9ac50c8',
                        'label' => 'Employer',
                        'name' => '',
                        'type' => 'tab',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                        'placement' => 'top',
                        'endpoint' => 0,
                    ],
                    [
                        'key' => 'field_600732abbd03a',
                        'label' => 'Contact us URL',
                        'name' => 'contact_us_url',
                        'type' => 'link',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                        'return_format' => 'url',
                    ],
                    [
                        'key' => 'field_5ff88cb4c50c9',
                        'label' => 'Post New Job',
                        'name' => 'post_new_job',
                        'type' => 'group',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                        'layout' => 'block',
                        'sub_fields' => [
                            [
                                'key' => 'field_5ff88cc8c50ca',
                                'label' => 'Benefits',
                                'name' => 'benefits',
                                'type' => 'repeater',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => [
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ],
                                'collapsed' => '',
                                'min' => 0,
                                'max' => 0,
                                'layout' => 'table',
                                'button_label' => 'Add Benefit',
                                'sub_fields' => [
                                    [
                                        'key' => 'field_5ffc96256f2a4',
                                        'label' => 'Option key',
                                        'name' => 'key',
                                        'type' => 'text',
                                        'instructions' => '',
                                        'required' => 0,
                                        'conditional_logic' => 0,
                                        'wrapper' => [
                                            'width' => '20',
                                            'class' => '',
                                            'id' => '',
                                        ],
                                        'default_value' => '',
                                        'placeholder' => '',
                                        'prepend' => '',
                                        'append' => '',
                                        'maxlength' => '',
                                    ],
                                    [
                                        'key' => 'field_5ff88cdac50cb',
                                        'label' => 'Benefit Name',
                                        'name' => 'name',
                                        'type' => 'text',
                                        'instructions' => '',
                                        'required' => 0,
                                        'conditional_logic' => 0,
                                        'wrapper' => [
                                            'width' => '80',
                                            'class' => '',
                                            'id' => '',
                                        ],
                                        'default_value' => '',
                                        'placeholder' => 'Medical Insurance',
                                        'prepend' => '',
                                        'append' => '',
                                        'maxlength' => '',
                                    ],
                                ],
                            ],
                            [
                                'key' => 'field_5ff88d0fc50cc',
                                'label' => 'Currency SSD',
                                'name' => 'currency',
                                'type' => 'repeater',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => [
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ],
                                'collapsed' => '',
                                'min' => 0,
                                'max' => 0,
                                'layout' => 'table',
                                'button_label' => 'Add currency',
                                'sub_fields' => [
                                    [
                                        'key' => 'field_currency_symbol',
                                        'label' => 'Currency symbol',
                                        'name' => 'symbol',
                                        'type' => 'text',
                                        'instructions' => '',
                                        'required' => 0,
                                        'conditional_logic' => 0,
                                        'wrapper' => [
                                            'width' => '20',
                                            'class' => '',
                                            'id' => '',
                                        ],
                                        'default_value' => '',
                                        'placeholder' => '',
                                        'prepend' => '',
                                        'append' => '',
                                        'maxlength' => '',
                                    ],
                                ],
                            ],
                            [
                                'key' => 'field_5ff88e21ace4a',
                                'label' => 'Compensation Period',
                                'name' => 'compensation_period',
                                'type' => 'repeater',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => [
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ],
                                'collapsed' => '',
                                'min' => 0,
                                'max' => 0,
                                'layout' => 'table',
                                'button_label' => 'Add Name of period',
                                'sub_fields' => [
                                    [
                                        'key' => 'field_5ffc959c3013c',
                                        'label' => 'Option key',
                                        'name' => 'key',
                                        'type' => 'text',
                                        'instructions' => '',
                                        'required' => 0,
                                        'conditional_logic' => 0,
                                        'wrapper' => [
                                            'width' => '20',
                                            'class' => '',
                                            'id' => '',
                                        ],
                                        'default_value' => '',
                                        'placeholder' => '',
                                        'prepend' => '',
                                        'append' => '',
                                        'maxlength' => '',
                                    ],
                                    [
                                        'key' => 'field_5ff88e34ace4b',
                                        'label' => 'Name',
                                        'name' => 'name',
                                        'type' => 'text',
                                        'instructions' => '',
                                        'required' => 0,
                                        'conditional_logic' => 0,
                                        'wrapper' => [
                                            'width' => '80',
                                            'class' => '',
                                            'id' => '',
                                        ],
                                        'default_value' => 'Annualy',
                                        'placeholder' => 'Annualy',
                                        'prepend' => '',
                                        'append' => '',
                                        'maxlength' => '',
                                    ],
                                ],
                            ],
                            [
                                'key' => 'field_5ff88dbebf0ab',
                                'label' => 'Agreement Options',
                                'name' => 'agreement_options',
                                'type' => 'repeater',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => [
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ],
                                'collapsed' => '',
                                'min' => 0,
                                'max' => 0,
                                'layout' => 'table',
                                'button_label' => 'Add option',
                                'sub_fields' => [
                                    [
                                        'key' => 'field_5ff8aa6cd2357',
                                        'label' => 'Option key',
                                        'name' => 'key',
                                        'type' => 'text',
                                        'instructions' => '',
                                        'required' => 0,
                                        'conditional_logic' => 0,
                                        'wrapper' => [
                                            'width' => '20',
                                            'class' => '',
                                            'id' => '',
                                        ],
                                        'default_value' => '',
                                        'placeholder' => '',
                                        'prepend' => '',
                                        'append' => '',
                                        'maxlength' => '',
                                    ],
                                    [
                                        'key' => 'field_5ff88dd7bf0ac',
                                        'label' => 'Agreement Name',
                                        'name' => 'name',
                                        'type' => 'text',
                                        'instructions' => '',
                                        'required' => 0,
                                        'conditional_logic' => 0,
                                        'wrapper' => [
                                            'width' => '80',
                                            'class' => '',
                                            'id' => '',
                                        ],
                                        'default_value' => '',
                                        'placeholder' => '',
                                        'prepend' => '',
                                        'append' => '',
                                        'maxlength' => '',
                                    ],
                                ],
                            ],
                        ],
                    ],
                ],
                'location' => [
                    [
                        [
                            'param' => 'options_page',
                            'operator' => '==',
                            'value' => 'site-settings',
                        ],
                    ],
                ],
                'menu_order' => 1,
                'position' => 'normal',
                'style' => 'default',
                'label_placement' => 'top',
                'instruction_placement' => 'label',
                'hide_on_screen' => '',
                'active' => true,
                'description' => '',
            ]
        );
    }

    private function cvFields()
    {
        acf_add_local_field_group(
            [
                'key' => 'group_5ff0b4545ebe4',
                'title' => 'General Info',
                'fields' => [
                    [
                        'key' => 'field_5ff0b464baff2',
                        'label' => 'Full Name',
                        'name' => 'full_name',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                    ],
                    [
                        'key' => 'field_5ff0b496baff3',
                        'label' => 'Headline (optional)',
                        'name' => 'headline',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                    ],                    [
                        'key' => 'field_salary_expectations',
                        'label' => 'Salary Expectations',
                        'name' => '',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                    ],
                    [
                        'key' => 'field_5ff0b49ebaff4',
                        'label' => 'Location',
                        'name' => 'location',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                        'default_value' => '0',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                    ],
                    [
                        'key' => 'field_5ff0b4a2baff5',
                        'label' => 'ZIP / Postal Code',
                        'name' => 'zip_code',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                    ],
                    [
                        'key' => 'field_5ff0b4b9baff6',
                        'label' => 'I am willing to relocate',
                        'name' => 'relocate',
                        'type' => 'true_false',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                        'message' => '',
                        'default_value' => 0,
                        'ui' => 1,
                        'ui_on_text' => 'Yes',
                        'ui_off_text' => 'No',
                    ],
                    [
                        'key' => 'field_5ff0b50a12bf5',
                        'label' => 'Public Email',
                        'name' => 'public_email',
                        'type' => 'email',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                    ],
                    [
                        'key' => 'field_5ff0b52b12bf6',
                        'label' => 'Is email confirmed',
                        'name' => 'is_email_confirmed',
                        'type' => 'true_false',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                        'message' => '',
                        'default_value' => 0,
                        'ui' => 0,
                        'ui_on_text' => '',
                        'ui_off_text' => '',
                    ],
                    [
                        'key' => 'field_5ff0b55712bf7',
                        'label' => 'Phone',
                        'name' => 'phone',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                    ],
                    [
                        'key' => 'field_5ff0b56712bf8',
                        'label' => 'Website',
                        'name' => 'website',
                        'type' => 'url',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                        'default_value' => '',
                        'placeholder' => '',
                    ],
                    [
                        'key' => 'field_5ff0b57912bf9',
                        'label' => 'Twitter Profile',
                        'name' => 'twitter',
                        'type' => 'url',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                        'default_value' => '',
                        'placeholder' => '',
                    ],
                    [
                        'key' => 'field_5ff0b58212bfa',
                        'label' => 'LinkedIn Profile',
                        'name' => 'linkedin',
                        'type' => 'url',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                        'default_value' => '',
                        'placeholder' => '',
                    ],
                    [
                        'key' => 'field_5ff0b59012bfb',
                        'label' => 'Facebook Profile',
                        'name' => 'facebook',
                        'type' => 'url',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                        'default_value' => '',
                        'placeholder' => '',
                    ],
                    [
                        'key' => 'field_5ff0a8681147c',
                        'label' => 'Let Employers Find You',
                        'name' => 'visibility',
                        'type' => 'true_false',
                        'instructions' => 'Private: Your profile is not publicly accessible. However, it is viewable as a part of your applications.',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                        'message' => '',
                        'default_value' => 0,
                        'ui' => 1,
                        'ui_on_text' => 'Visible',
                        'ui_off_text' => 'Hidden',
                    ],
                    [
                        'key' => 'field_5ff0a9161147d',
                        'label' => 'Work Experience',
                        'name' => 'work_experience',
                        'type' => 'repeater',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                        'collapsed' => '',
                        'min' => 0,
                        'max' => 0,
                        'layout' => 'table',
                        'button_label' => '',
                        'sub_fields' => [
                            [
                                'key' => 'field_5ff0a9361147e',
                                'label' => 'Job Position',
                                'name' => 'job_position',
                                'type' => 'text',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => [
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ],
                                'default_value' => 'web designer',
                                'placeholder' => 'web designer',
                                'prepend' => '',
                                'append' => '',
                                'maxlength' => '',
                            ],
                            [
                                'key' => 'field_5ff0a95d1147f',
                                'label' => 'Company Name',
                                'name' => 'company_name',
                                'type' => 'text',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => [
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ],
                                'default_value' => 'Company Name',
                                'placeholder' => 'Company Name',
                                'prepend' => '',
                                'append' => '',
                                'maxlength' => '',
                            ],
                            [
                                'key' => 'field_5ff0a98111480',
                                'label' => 'Period',
                                'name' => 'period',
                                'type' => 'group',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => [
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ],
                                'layout' => 'block',
                                'sub_fields' => [
                                    [
                                        'key' => 'field_5ff0a9b511481',
                                        'label' => 'from',
                                        'name' => 'from',
                                        'type' => 'date_picker',
                                        'instructions' => '',
                                        'required' => 0,
                                        'conditional_logic' => 0,
                                        'wrapper' => [
                                            'width' => '',
                                            'class' => '',
                                            'id' => '',
                                        ],
                                        'display_format' => 'F j, Y',
                                        'return_format' => 'F j, Y',
                                        'first_day' => 1,
                                    ],
                                    [
                                        'key' => 'field_5ff0a9c711482',
                                        'label' => 'to',
                                        'name' => 'to',
                                        'type' => 'date_picker',
                                        'instructions' => '',
                                        'required' => 0,
                                        'conditional_logic' => 0,
                                        'wrapper' => [
                                            'width' => '',
                                            'class' => '',
                                            'id' => '',
                                        ],
                                        'display_format' => 'F j, Y',
                                        'return_format' => 'F j, Y',
                                        'first_day' => 1,
                                    ],
                                ],
                            ],
                            [
                                'key' => 'field_5ff0a9f311483',
                                'label' => 'Description',
                                'name' => 'description',
                                'type' => 'textarea',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => [
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ],
                                'default_value' => 'Enthusiastic and self-motivated web designer with 3+ years of experience. Eager to join WebHouse to bring top-class frontend development, UX, and visual design skills. In previous roles redesigned a SaaS website that reduced CAC by 50%, and implemented an SEO-optimized design that boosted traffic by 300%.',
                                'placeholder' => 'Description',
                                'maxlength' => '',
                                'rows' => '',
                                'new_lines' => '',
                            ],
                        ],
                    ],
                    [
                        'key' => 'field_5ff0aae9f9acc',
                        'label' => 'Education',
                        'name' => 'education',
                        'type' => 'repeater',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                        'collapsed' => '',
                        'min' => 0,
                        'max' => 0,
                        'layout' => 'table',
                        'button_label' => '',
                        'sub_fields' => [
                            [
                                'key' => 'field_5ff0ab13f9acd',
                                'label' => 'Name',
                                'name' => 'name',
                                'type' => 'text',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => [
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ],
                                'default_value' => '',
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                                'maxlength' => '',
                            ],
                            [
                                'key' => 'field_5ff0ab2bf9ace',
                                'label' => 'Degree',
                                'name' => 'degree',
                                'type' => 'text',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => [
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ],
                                'default_value' => 'No Degree',
                                'placeholder' => 'No Degree',
                                'prepend' => '',
                                'append' => '',
                                'maxlength' => '',
                            ],
                            [
                                'key' => 'field_5ff0ab55f9acf',
                                'label' => 'Major or field of study',
                                'name' => 'fields_of_study',
                                'type' => 'text',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => [
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ],
                                'default_value' => '',
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                                'maxlength' => '',
                            ],
                            [
                                'key' => 'field_5ff0abacf9ad0',
                                'label' => 'Description',
                                'name' => 'description',
                                'type' => 'textarea',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => [
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ],
                                'default_value' => '',
                                'placeholder' => 'Description',
                                'maxlength' => '',
                                'rows' => '',
                                'new_lines' => '',
                            ],
                            [
                                'key' => 'field_5ff0ac5cd32e9',
                                'label' => 'Period',
                                'name' => 'period',
                                'type' => 'group',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => [
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ],
                                'layout' => 'block',
                                'sub_fields' => [
                                    [
                                        'key' => 'field_5ff0ac7dd32ea',
                                        'label' => 'from',
                                        'name' => 'from',
                                        'type' => 'date_picker',
                                        'instructions' => '',
                                        'required' => 0,
                                        'conditional_logic' => 0,
                                        'wrapper' => [
                                            'width' => '',
                                            'class' => '',
                                            'id' => '',
                                        ],
                                        'display_format' => 'Y',
                                        'return_format' => 'Y',
                                        'first_day' => 1,
                                    ],
                                    [
                                        'key' => 'field_5ff0ac95d32eb',
                                        'label' => 'to',
                                        'name' => 'to',
                                        'type' => 'date_picker',
                                        'instructions' => '',
                                        'required' => 0,
                                        'conditional_logic' => 0,
                                        'wrapper' => [
                                            'width' => '',
                                            'class' => '',
                                            'id' => '',
                                        ],
                                        'display_format' => 'Y',
                                        'return_format' => 'Y',
                                        'first_day' => 1,
                                    ],
                                ],
                            ],
                        ],
                    ],
                ],
                'location' => [
                    [
                        [
                            'param' => 'post_type',
                            'operator' => '==',
                            'value' => 'cv',
                        ],
                    ],
                ],
                'menu_order' => 0,
                'position' => 'normal',
                'style' => 'default',
                'label_placement' => 'top',
                'instruction_placement' => 'label',
                'hide_on_screen' => '',
                'active' => true,
                'description' => '',
            ]
        );
    }

    private function userFields()
    {
        acf_add_local_field_group(
            [
                'key' => 'group_5ff1bdc727371',
                'title' => 'Extended user settings',
                'fields' => [
                    [
                        'key' => 'field_5ff1bdf01984d',
                        'label' => 'Photo',
                        'name' => 'photo',
                        'type' => 'image',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                        'return_format' => 'url',
                        'preview_size' => 'medium',
                        'library' => 'uploadedTo',
                        'min_width' => '',
                        'min_height' => '',
                        'min_size' => '',
                        'max_width' => '',
                        'max_height' => '',
                        'max_size' => '',
                        'mime_types' => '',
                    ],
                ],
                'location' => [
                    [
                        [
                            'param' => 'user_form',
                            'operator' => '==',
                            'value' => 'edit',
                        ],
                    ],
                ],
                'menu_order' => 0,
                'position' => 'normal',
                'style' => 'default',
                'label_placement' => 'top',
                'instruction_placement' => 'label',
                'hide_on_screen' => '',
                'active' => true,
                'description' => '',
            ]
        );
    }

    private function employerFields()
    {
        acf_add_local_field_group(
            [
                'key' => 'group_5ff1f2fc6b631',
                'title' => 'Employer Data',
                'fields' => [
                    [
                        'key' => 'field_5ff1f319b9bd4',
                        'label' => 'Is Activated',
                        'name' => 'is_activated',
                        'type' => 'true_false',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                        'message' => '',
                        'default_value' => 0,
                        'ui' => 1,
                        'ui_on_text' => 'Premium',
                        'ui_off_text' => 'Standart',
                    ],
                    [
                        'key' => 'field_5ff1f3b6b9bd5',
                        'label' => 'Avaible credits',
                        'name' => 'avaible_credits',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                        'default_value' => 0,
                        'placeholder' => '$0.00',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                    ],
                ],
                'location' => [
                    [
                        [
                            'param' => 'user_role',
                            'operator' => '==',
                            'value' => 'employer',
                        ],
                    ],
                ],
                'menu_order' => 0,
                'position' => 'normal',
                'style' => 'default',
                'label_placement' => 'top',
                'instruction_placement' => 'label',
                'hide_on_screen' => '',
                'active' => true,
                'description' => '',
            ]
        );
    }

    private function contactUsFields(): void
    {
        acf_add_local_field_group(
            [
                'key' => 'group_page_contact_us',
                'title' => 'Extended user settings',
                'fields' => [
                    [
                        'key' => 'field_phone',
                        'label' => 'Photo',
                        'name' => 'photo',
                        'type' => 'image',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                        'return_format' => 'url',
                        'preview_size' => 'medium',
                        'library' => 'uploadedTo',
                        'min_width' => '',
                        'min_height' => '',
                        'min_size' => '',
                        'max_width' => '',
                        'max_height' => '',
                        'max_size' => '',
                        'mime_types' => '',
                    ],
                ],
                'location' => [
                    [
                        [
                            'param' => 'user_form',
                            'operator' => '==',
                            'value' => 'edit',
                        ],
                    ],
                ],
                'menu_order' => 0,
                'position' => 'normal',
                'style' => 'default',
                'label_placement' => 'top',
                'instruction_placement' => 'label',
                'hide_on_screen' => '',
                'active' => true,
                'description' => '',
            ]
        );
    }

    public function benefitsChoices($field)
    {
        $settings = SiteSettings::getJobSettings();
        $jobService = $settings['benefits'] ?? [];
        return $this->prepareFieldChoices($jobService, $field);
    }

    public function agreementChoices($field)
    {
        $settings = SiteSettings::getJobSettings();
        $jobService = $settings['agreement_options'] ?? [];
        return $this->prepareFieldChoices($jobService, $field);
    }

    public function currencyChoices($field)
    {
        $settings = SiteSettings::getJobSettings();
        $jobService = $settings['currency'] ?? [];
        return $this->prepareFieldChoices($jobService, $field);
    }

    public function compensationPeriodChoices($field)
    {
        $settings = SiteSettings::getJobSettings();
        $jobService = $settings['compensation_period'] ?? [];
        return $this->prepareFieldChoices($jobService, $field);
    }

    private function prepareFieldChoices($items, $field)
    {
        foreach ($items as $id => $item) {
            $key = strtolower(trim(preg_replace('/[^A-Za-z0-9-]+/', '-', $item['key'] ?? $item['name'])));
            $field['choices'][$key] = $item['name'];
        }
        return $field;
    }
}